name: Debug API Key Replacement

on:
  push:
    branches:
      - main  # Adjust this if needed

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print API Key (Debugging)
        run: echo "API Key is: ${{ secrets.TMDB_API_KEY }}"
